#!/bin/bash
set -euo pipefail

# =============================================================================
# bootstrap.sh — ibus-handwrite-chinese installer + post-install fixes + verify
#
# Usage: sudo bash bootstrap.sh
#
# Combines the upstream install with all fixes and auto-verification so that
# running this script is the *only* command needed to install and fully
# configure Chinese handwriting input on Linux Mint / Debian / Ubuntu.
# =============================================================================

# --- Constants ---------------------------------------------------------------
UPSTREAM_REPO="https://github.com/ai-space-lab/ibus-handwrite-chinese.git"
SRC_DIR="/tmp/ibus-handwrite-chinese-src"
THIS_DIR="$(cd "$(dirname "$0")" && pwd)"
ROLLBACK_FILE="/tmp/ibus-fix-rollback.sh"

# =============================================================================
# PHASE 1 — Upstream install
# =============================================================================
phase1_upstream_install() {
  echo ""
  echo "=== PHASE 1: Upstream install ==="

  # 1. Check root
  if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run as root (sudo)." >&2
    exit 1
  fi

  # 2. Detect distro family
  local distro=""
  if [ -f /etc/os-release ]; then
    . /etc/os-release
    case "${ID:-}" in
      debian|ubuntu|linuxmint|neon|pop|elementary|zorin|kali) distro="debian" ;;
      fedora|rhel|centos|rocky|alma)                       distro="fedora" ;;
      arch|manjaro|endeavouros|arcolinux)                   distro="arch" ;;
      suse|opensuse|sles)                                   distro="suse" ;;
    esac
  fi

  if [ -z "$distro" ]; then
    echo "ERROR: Unsupported distro. Only Debian/Ubuntu, Fedora, Arch, and openSUSE are supported." >&2
    exit 1
  fi
  echo "Detected distro family: $distro"

  # 3. Install dependencies
  case "$distro" in
    debian)
      apt update
      apt install -y python3-evdev wget unzip p7zip-full git python3-venv
      ;;
    fedora)
      dnf install -y python3-evdev wget unzip p7zip git python3-virtualenv
      ;;
    arch)
      pacman -S --noconfirm python-evdev wget unzip p7zip git python-virtualenv
      ;;
    suse)
      zypper install -y python3-evdev wget unzip p7zip-full git python3-venv
      ;;
  esac

  # 4. Clone or use local repo
  if [ -d "$THIS_DIR/.git" ]; then
    echo "Local git repo detected at $THIS_DIR — using it as source."
    SRC_DIR="$THIS_DIR"
  else
    rm -rf "$SRC_DIR"
    git clone --depth 1 "$UPSTREAM_REPO" "$SRC_DIR"
  fi

  # 5. Run install.sh from within SRC_DIR (it uses relative paths)
  if [ -f "$SRC_DIR/tools/install.sh" ]; then
    (cd "$SRC_DIR" && bash tools/install.sh --skip-deps)
  else
    echo "ERROR: install.sh not found at $SRC_DIR/tools/install.sh" >&2
    exit 1
  fi

  echo "PHASE 1 complete."
}

# =============================================================================
# PHASE 2 — Post-install fixes
# =============================================================================
phase2_post_install_fixes() {
  echo ""
  echo "=== PHASE 2: Post-install fixes ==="

  local REAL_USER="${SUDO_USER:-$USER}"

  # Wayland warning
  if [ "${XDG_SESSION_TYPE:-}" = "wayland" ]; then
    echo "⚠ WARNING: Wayland session detected. Floating panel positioning may not work (upstream limitation)."
  fi

  # Initialize rollback script
  cat > "$ROLLBACK_FILE" << 'ROLLBACK_HEADER'
#!/bin/bash
# ibus-handwrite-chinese fix rollback
# Generated by bootstrap.sh
ROLLBACK_HEADER

  local FAILED=0

  # Helper: run a critical fix; abort on failure.
  run_critical_fix() {
    local label="$1"
    shift
    if eval "$@"; then
      echo "  ✅ $label"
    else
      echo "  ❌ $label — aborting"
      exit 1
    fi
  }

  # Helper: append a rollback command
  add_rollback() {
    echo "$1" >> "$ROLLBACK_FILE"
  }

  # --------------------------------------------------------------------------
  # Fix 1: Symlink handwrite_evdev.py into engine directory
  # --------------------------------------------------------------------------
  run_critical_fix "Fix 1: Symlink handwrite_evdev.py into engine dir" \
    ln -sf /usr/local/bin/handwrite_evdev.py /usr/local/share/ibus-handwrite-chinese/handwrite_evdev.py
  add_rollback "rm -f /usr/local/share/ibus-handwrite-chinese/handwrite_evdev.py"

  # --------------------------------------------------------------------------
  # Fix 2: Add real user to input group
  # --------------------------------------------------------------------------
  run_critical_fix "Fix 2: Add user '$REAL_USER' to input group" \
    usermod -a -G input "$REAL_USER"
  add_rollback "gpasswd -d \"$REAL_USER\" input 2>/dev/null || true"

  # --------------------------------------------------------------------------
  # Fix 3: Update GTK3 immodules cache
  # --------------------------------------------------------------------------
  echo "  Fix 3: Updating GTK3 immodules cache..."
  local GTK_QUERY=""
  GTK_QUERY=$(dpkg -L libgtk-3-0t64 2>/dev/null | grep '/gtk-query-immodules-3.0$' | head -1 || true)
  if [ -z "$GTK_QUERY" ]; then
    GTK_QUERY=$(find /usr/lib -name 'gtk-query-immodules-3.0' -type f -o -type l 2>/dev/null | head -1 || true)
  fi
  if [ -n "$GTK_QUERY" ]; then
    if "$GTK_QUERY" --update-cache; then
      echo "    ✅ GTK immodules cache updated ($GTK_QUERY)"
    else
      echo "    ⚠ WARNING: gtk-query-immodules-3.0 --update-cache returned non-zero"
    fi
  else
    echo "    ⚠ WARNING: gtk-query-immodules-3.0 not found — skipping cache update"
  fi
  add_rollback "# GTK immodules cache update has no rollback"

  # --------------------------------------------------------------------------
  # Fix 4: Set preload-engines dconf (as REAL_USER with proper D-Bus)
  # --------------------------------------------------------------------------
  echo "  Fix 4: Setting preload-engines..."
  local HAS_GSETTINGS=false
  if command -v gsettings &>/dev/null && command -v dbus-launch &>/dev/null; then
    HAS_GSETTINGS=true
  fi

  if $HAS_GSETTINGS; then
    if sudo -u "$REAL_USER" DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-}" \
      gsettings set org.freedesktop.ibus.general preload-engines "['xkb:us::eng', 'handwrite-chinese']" 2>/dev/null; then
      echo "    ✅ preload-engines set via gsettings"
    else
      echo "    ⚠ WARNING: Could not set preload-engines via gsettings (no D-Bus session). Trying dconf fallback..."
      if command -v dconf &>/dev/null; then
        if sudo -u "$REAL_USER" DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-}" \
          dconf write /desktop/ibus/general/preload-engines "['xkb:us::eng', 'handwrite-chinese']" 2>/dev/null; then
          echo "    ✅ preload-engines set via dconf"
        else
          echo "    ⚠ WARNING: dconf fallback also failed. User must log out/in."
        fi
      else
        echo "    ⚠ WARNING: Could not set preload-engines (no gsettings or dconf). User must log out/in."
      fi
    fi
  else
    echo "    ⚠ WARNING: gsettings not available. Trying dconf fallback..."
    if command -v dconf &>/dev/null; then
      if sudo -u "$REAL_USER" DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-}" \
        dconf write /desktop/ibus/general/preload-engines "['xkb:us::eng', 'handwrite-chinese']" 2>/dev/null; then
        echo "    ✅ preload-engines set via dconf"
      else
        echo "    ⚠ WARNING: dconf fallback also failed. User must log out/in."
      fi
    else
      echo "    ⚠ WARNING: Could not set preload-engines (no gsettings or dconf). User must log out/in."
    fi
  fi
  add_rollback "# preload-engines reset (user must undo manually if desired)"

  # --------------------------------------------------------------------------
  # Fix 5: Kill stale root ibus-daemon
  # --------------------------------------------------------------------------
  echo "  Fix 5: Killing stale root ibus-daemon..."
  if ps aux 2>/dev/null | grep -q 'root.*ibus-daemon'; then
    pkill -u root ibus-daemon 2>/dev/null || true
    sleep 1
    echo "    ✅ Root ibus-daemon killed"
  else
    echo "    ✅ No stale root ibus-daemon found"
  fi
  add_rollback "# ibus-daemon restart not rolled back"

  # --------------------------------------------------------------------------
  # Fix 6: Restart ibus-daemon with panel & poll for engine registration
  # --------------------------------------------------------------------------
  echo "  Fix 6: Restarting ibus-daemon..."
  ibus-daemon --daemonize --replace --panel=/usr/libexec/ibus-ui-gtk3 2>/dev/null || true
  local registered=false
  for i in $(seq 1 10); do
    if ibus list-engine 2>/dev/null | grep -q handwrite; then
      registered=true
      echo "    ✅ Engine registered in IBus (after ${i}s)"
      break
    fi
    sleep 1
  done
  if [ "$registered" = false ]; then
    echo "    ⚠ WARNING: Engine did not register within 10s — checks below may fail."
    echo "      Try manually: ibus-daemon --daemonize --replace --panel=/usr/libexec/ibus-ui-gtk3"
    echo "      Then: ibus engine handwrite-chinese"
  fi
  add_rollback "# ibus-daemon restart not rolled back"

  # --------------------------------------------------------------------------
  # Fix 7: Switch to handwrite-chinese engine
  # --------------------------------------------------------------------------
  echo "  Fix 7: Switching to handwrite-chinese engine..."
  if ibus engine handwrite-chinese 2>/dev/null; then
    echo "    ✅ Engine switched to handwrite-chinese"
  else
    echo "    ⚠ WARNING: Could not switch to handwrite-chinese engine. Try: ibus engine handwrite-chinese"
  fi
  add_rollback "# engine switch not rolled back"

  # --------------------------------------------------------------------------
  # Fix 8: Update stale version strings (0.1.0 → 0.3.1) — cosmetic
  # --------------------------------------------------------------------------
  echo "  Fix 8: Updating version strings..."
  local VERSION_FILE="/usr/local/share/ibus-handwrite-chinese/ibus-engine-handwrite-chinese"
  local COMPONENT_FILE="/usr/share/ibus/component/handwrite-chinese.xml"

  if [ -f "$VERSION_FILE" ]; then
    sed -i 's/"0.1.0",\s*$/"0.3.1",/' "$VERSION_FILE" || true
    echo "    ✅ Version updated in engine file"
  else
    echo "    ⚠ WARNING: $VERSION_FILE not found — skipping"
  fi

  if [ -f "$COMPONENT_FILE" ]; then
    sed -i 's|<version>0.1.0</version>|<version>0.3.1</version>|' "$COMPONENT_FILE" || true
    echo "    ✅ Version updated in component XML"
  else
    echo "    ⚠ WARNING: $COMPONENT_FILE not found — skipping"
  fi
  add_rollback "# version string changes not rolled back"

  # --------------------------------------------------------------------------
  # Fix 9: Fix docstring/variable name (avg_probs → peak_probs) — cosmetic
  # --------------------------------------------------------------------------
  echo "  Fix 9: Fixing docstring and variable name (avg_probs → peak_probs)..."
  if [ -f "$VERSION_FILE" ]; then
    sed -i 's/average softmax across time/max pooling across time/' "$VERSION_FILE" || true
    sed -i 's/avg_probs/peak_probs/g' "$VERSION_FILE" || true
    echo "    ✅ Docstring and variable name fixed"
  else
    echo "    ⚠ WARNING: $VERSION_FILE not found — skipping"
  fi
  add_rollback "# avg_probs → peak_probs not rolled back"

  # Finalize rollback script
  chmod +x "$ROLLBACK_FILE"
  echo ""
  echo "PHASE 2 complete. Rollback saved at $ROLLBACK_FILE"
}

# =============================================================================
# PHASE 3 — Verification
# =============================================================================
phase3_verification() {
  echo ""
  echo "=== PHASE 3: Verification ==="

  local REAL_USER="${SUDO_USER:-$USER}"
  local FAILED=0

  check() {
    local label="$1" cmd="$2"
    if eval "$cmd" >/dev/null 2>&1; then
      echo "  ✅ $label"
    else
      echo "  ❌ $label"
      FAILED=$((FAILED + 1))
    fi
  }

  check "Engine registered in ibus list-engine" \
    'ibus list-engine 2>/dev/null | grep -q handwrite-chinese'

  check "Engine active (ibus engine = handwrite-chinese)" \
    '[ "$(ibus engine 2>/dev/null)" = "handwrite-chinese" ]'

  check "Engine process running" \
    'pgrep -f ibus-engine-handwrite >/dev/null'

  check "Panel process running" \
    'pgrep -f ibus-ui-gtk3 >/dev/null'

  check "User in input group" \
    "groups ${REAL_USER} 2>/dev/null | grep -q input"

  check "handwrite_evdev importable from engine dir" \
    '/usr/local/share/ibus-handwrite-chinese/venv/bin/python3 -c "import sys; sys.path.insert(0, '\''/usr/local/share/ibus-handwrite-chinese'\''); import handwrite_evdev" 2>/dev/null'

  check "Version strings updated to 0.3.1" \
    'grep -q '\''"0.3.1"'\'' /usr/local/share/ibus-handwrite-chinese/ibus-engine-handwrite-chinese'

  echo ""
  if [ "$FAILED" -gt 0 ]; then
    echo "❌ $FAILED check(s) failed"
    exit 1
  else
    echo "✅ All checks passed"
  fi
}

# =============================================================================
# Main
# =============================================================================
phase1_upstream_install
phase2_post_install_fixes
phase3_verification

echo ""
echo "=== Installation complete ==="
echo "Log out and back in (or restart IBus with: ibus-daemon --daemonize --replace)"
echo "Then select 'Chinese (Handwrite)' from your IBus input-method selector."
