#!/usr/bin/env python3
"""GTK3 preference dialog for ibus-handwrite-chinese.

Provides a 6-tab notebook UI that reads/writes the TOML config file at
``~/.config/ibus-handwrite-chinese/config.toml``.

Exports:
    main() — launches the GTK window (standalone or from engine ``--setup``).
"""

import copy
import os
import sys
import threading

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('Gdk', '3.0')
from gi.repository import GLib, Gtk, Gdk

# Ensure src directory is in path for sibling imports
_handwrite_dir = os.path.dirname(os.path.abspath(__file__))
if _handwrite_dir not in sys.path:
    sys.path.insert(0, _handwrite_dir)

import handwrite_config
import handwrite_model_download
import handwrite_shortcuts
import handwrite_userdict


# ---------------------------------------------------------------------------
# Simple TOML writer (no tomli-w dependency)
# ---------------------------------------------------------------------------

def _write_toml_value(f, value):
    """Write a single TOML value to open file *f*."""
    if isinstance(value, bool):
        f.write("true" if value else "false")
    elif isinstance(value, int):
        f.write(str(value))
    elif isinstance(value, float):
        f.write(str(value))
    elif isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        f.write('"' + escaped + '"')
    else:
        raise TypeError(f"Unsupported TOML type: {type(value)}")


def write_toml(config, filepath):
    """Write *config* dict to *filepath* in TOML format.

    Only non-default keys are written (keeps the config file clean).
    Missing parent directories are created automatically.
    """
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    defaults = handwrite_config.DEFAULT_CONFIG

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("# ibus-handwrite-chinese configuration\n")
        f.write("# Auto-generated by handwrite_prefs.py\n\n")

        for section_name in sorted(config.keys()):
            section = config[section_name]
            default_section = defaults.get(section_name, {})

            # Collect only keys that differ from defaults
            non_default = {}
            for key, value in section.items():
                if value != default_section.get(key):
                    non_default[key] = value

            if not non_default:
                continue

            f.write(f"[{section_name}]\n")
            for key in sorted(non_default.keys()):
                value = non_default[key]
                f.write(f"{key} = ")
                _write_toml_value(f, value)
                f.write("\n")
            f.write("\n")


# ---------------------------------------------------------------------------
# Key Capture Entry
# ---------------------------------------------------------------------------

class KeyCaptureEntry(Gtk.Entry):
    """Entry widget that captures a single keybinding on click.

    Displays the current binding in readable format via
    :func:`handwrite_shortcuts.format_for_display`.  On click, enters capture
    mode; the next keypress (with optional modifiers) is validated via
    :func:`handwrite_shortcuts.validate_binding` and stored.
    """

    # Modifier-only keys we ignore during capture
    _MODIFIER_KEYS = frozenset({
        "Shift_L", "Shift_R", "Control_L", "Control_R",
        "Alt_L", "Alt_R", "Meta_L", "Meta_R",
        "Super_L", "Super_R", "Hyper_L", "Hyper_R",
    })

    def __init__(self, action, initial_key_string, on_change=None):
        super().__init__()
        self._action = action
        self._key_string = initial_key_string
        self._on_change = on_change
        self._capturing = False
        self.set_editable(False)
        self.set_can_focus(True)
        self.set_width_chars(22)
        self._update_display()
        self.connect("button-press-event", self._on_click)
        self.connect("key-press-event", self._on_key_press)
        self.connect("focus-out-event", self._on_focus_out)

    # -- public accessors ---------------------------------------------------

    def get_key_string(self):
        """Return the raw key binding string stored in this entry."""
        return self._key_string

    def set_key_string(self, key_string):
        """Replace the binding and refresh the display."""
        self._key_string = key_string
        self._update_display()

    # -- internal -----------------------------------------------------------

    def _update_display(self):
        display = handwrite_shortcuts.format_for_display(
            self._action, {self._action: self._key_string}
        )
        self.set_text(display)

    def _start_capture(self):
        self._capturing = True
        self.set_text("… press key …")
        self.grab_focus()

    def _stop_capture(self):
        self._capturing = False
        self._update_display()

    def _on_click(self, _widget, _event):
        if not self._capturing:
            self._start_capture()
        return True

    def _on_focus_out(self, _widget, _event):
        if self._capturing:
            self._stop_capture()
        return False

    def _on_key_press(self, _widget, event):
        if not self._capturing:
            return False

        keyval = event.get_keyval()[1]
        key_name = Gdk.keyval_name(keyval)
        if key_name is None or key_name in self._MODIFIER_KEYS:
            return True

        # Build modifier prefix from keyboard state
        state = event.get_state()
        mods = []
        if state & Gdk.ModifierType.CONTROL_MASK:
            mods.append("Control")
        if state & Gdk.ModifierType.SHIFT_MASK:
            mods.append("Shift")
        if state & Gdk.ModifierType.MOD1_MASK:
            mods.append("Alt")
        if state & Gdk.ModifierType.SUPER_MASK:
            mods.append("Super")

        key_string = (
            "<" + "><".join(sorted(mods)) + ">" + key_name
            if mods
            else key_name
        )

        # Validate
        error = handwrite_shortcuts.validate_binding(key_string)
        if error:
            self.set_text(error)
            GLib.timeout_add_seconds(2, self._stop_capture)
            return True

        self._key_string = key_string
        self._capturing = False
        self._update_display()
        if self._on_change:
            self._on_change(self._action, key_string)
        return True


# ---------------------------------------------------------------------------
# Preferences Dialog
# ---------------------------------------------------------------------------

# Order and human-readable labels for shortcut actions
_SHORTCUT_ACTIONS = [
    "escape",
    "commit",
    "delete_stroke",
    "page_up",
    "page_down",
    "cycle_theme",
    "open_settings",
]

_SHORTCUT_LABELS = {
    "escape": "Escape",
    "commit": "Commit",
    "delete_stroke": "Delete Stroke",
    "page_up": "Page Up",
    "page_down": "Page Down",
    "cycle_theme": "Cycle Theme",
    "open_settings": "Open Settings",
}


class HandwritePrefs:
    """GTK3 preference dialog with a 6-tab notebook.

    Usage::

        prefs = HandwritePrefs()
        prefs.window.show_all()
        Gtk.main()
    """

    def __init__(self):
        self.config = handwrite_config.load_config()
        self.original_config = copy.deepcopy(self.config)
        self._shortcut_entries = {}  # action → KeyCaptureEntry
        self._download_in_progress = False
        self._pulse_id = None

        # Detect env-var overrides — we check for any IBUS_HANDWRITE_* that
        # maps to a known config key in ENV_MAP.
        self._env_active = any(
            k in os.environ for k in handwrite_config.ENV_MAP
        )

        self._build_ui()
        self._load_widget_values()
        self._refresh_model_info()
        self._refresh_user_dict_stats()

    # ------------------------------------------------------------------
    # Config path
    # ------------------------------------------------------------------

    @staticmethod
    def _get_config_path():
        xdg_config = os.environ.get("XDG_CONFIG_HOME", "")
        if not xdg_config:
            xdg_config = os.path.expanduser("~/.config")
        return os.path.join(xdg_config, "ibus-handwrite-chinese", "config.toml")

    # ------------------------------------------------------------------
    # UI construction
    # ------------------------------------------------------------------

    def _build_ui(self):
        self.window = Gtk.Window.new(Gtk.WindowType.TOPLEVEL)
        self.window.set_title("ibus-handwrite-chinese Preferences")
        self.window.set_default_size(720, 520)
        self.window.set_border_width(0)
        self.window.connect("destroy", Gtk.main_quit)
        self.window.set_position(Gtk.WindowPosition.CENTER)

        vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=0)
        self.window.add(vbox)

        # -- info bar (env overrides) --
        if self._env_active:
            info_bar = Gtk.InfoBar()
            info_bar.set_message_type(Gtk.MessageType.INFO)
            info_bar.set_show_close_button(True)
            info_bar.connect("response", lambda ib, _: ib.hide())
            content_area = info_bar.get_content_area()
            lbl = Gtk.Label(
                label="Some settings are overridden by IBUS_HANDWRITE_* environment variables"
            )
            content_area.add(lbl)
            vbox.pack_start(info_bar, False, False, 0)

        # -- notebook --
        notebook = Gtk.Notebook()
        vbox.pack_start(notebook, True, True, 0)

        self._create_general_tab(notebook)
        self._create_model_tab(notebook)
        self._create_engine_tab(notebook)
        self._create_window_tab(notebook)
        self._create_user_dict_tab(notebook)
        self._create_shortcuts_tab(notebook)

        # -- button bar --
        btn_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=8)
        btn_box.set_margin_top(6)
        btn_box.set_margin_bottom(6)
        btn_box.set_margin_start(8)
        btn_box.set_margin_end(8)

        reset_btn = Gtk.Button(label="Reset to Defaults")
        reset_btn.connect("clicked", self._on_reset)
        btn_box.pack_start(reset_btn, False, False, 0)

        cancel_btn = Gtk.Button(label="Cancel")
        cancel_btn.connect("clicked", self._on_cancel)
        btn_box.pack_end(cancel_btn, False, False, 0)

        apply_btn = Gtk.Button(label="Apply")
        apply_btn.get_style_context().add_class("suggested-action")
        apply_btn.connect("clicked", self._on_apply)
        btn_box.pack_end(apply_btn, False, False, 0)

        vbox.pack_start(btn_box, False, False, 0)

        # -- help footer --
        help_lbl = Gtk.Label(
            label=(
                "If the engine crashes, delete "
                "~/.config/ibus-handwrite-chinese/config.toml to restore defaults."
            )
        )
        ctx = help_lbl.get_style_context()
        ctx.add_class("dim-label")
        help_lbl.set_margin_bottom(4)
        help_lbl.set_margin_start(8)
        help_lbl.set_margin_end(8)
        help_lbl.set_halign(Gtk.Align.START)
        vbox.pack_start(help_lbl, False, False, 0)

    # -- helpers for tab construction ---------------------------------------

    @staticmethod
    def _make_spin(min_val, max_val, step=1):
        """Create a Gtk.SpinButton with an optional page-size increment."""
        adj = Gtk.Adjustment(value=min_val, lower=min_val,
                             upper=max_val, step_increment=step,
                             page_increment=step * 10)
        spin = Gtk.SpinButton(adjustment=adj)
        spin.set_numeric(True)
        return spin

    @staticmethod
    def _make_scale(min_val, max_val, step=0.05):
        """Create a horizontal Gtk.Scale with the given range."""
        scale = Gtk.Scale.new_with_range(
            Gtk.Orientation.HORIZONTAL, min_val, max_val, step
        )
        scale.set_digits(2)
        scale.set_size_request(200, -1)
        return scale

    @staticmethod
    def _make_combo(options):
        """Create a Gtk.ComboBoxText populated with *options* (id=text)."""
        combo = Gtk.ComboBoxText()
        for opt in options:
            combo.append(opt, opt.capitalize() if opt.islower() else opt)
        return combo

    def _add_grid_row(self, grid, row, label_text, widget,
                      label_align=Gtk.Align.START):
        """Add a labelled row to *grid* at *row* index.  Returns the label."""
        lbl = Gtk.Label(label=label_text)
        lbl.set_halign(label_align)
        lbl.set_margin_end(6)
        grid.attach(lbl, 0, row, 1, 1)
        widget.set_hexpand(True)
        grid.attach(widget, 1, row, 1, 1)
        return lbl

    # ------------------------------------------------------------------
    # Tab 1 — General
    # ------------------------------------------------------------------

    def _create_general_tab(self, notebook):
        grid = Gtk.Grid()
        grid.set_row_spacing(6)
        grid.set_column_spacing(6)
        grid.set_margin_top(12)
        grid.set_margin_bottom(12)
        grid.set_margin_start(12)
        grid.set_margin_end(12)
        grid.set_column_homogeneous(False)
        grid.set_border_width(0)

        row = 0

        # Theme
        self._theme_combo = self._make_combo(["dark", "light", "auto"])
        self._add_grid_row(grid, row, "Theme", self._theme_combo)
        row += 1

        # Log level
        self._log_level_combo = self._make_combo(
            ["DEBUG", "INFO", "WARNING", "ERROR"]
        )
        self._add_grid_row(grid, row, "Log Level", self._log_level_combo)
        row += 1

        # Log path — entry + browse button
        log_hbox = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=6)
        self._log_path_entry = Gtk.Entry()
        browse_btn = Gtk.Button(label="Browse…")
        browse_btn.connect("clicked", self._on_browse_log_path)
        log_hbox.pack_start(self._log_path_entry, True, True, 0)
        log_hbox.pack_start(browse_btn, False, False, 0)
        self._add_grid_row(grid, row, "Log Path", log_hbox)
        row += 1

        swin = Gtk.ScrolledWindow()
        swin.set_policy(Gtk.PolicyType.AUTOMATIC, Gtk.PolicyType.AUTOMATIC)
        swin.add(grid)
        notebook.append_page(swin, Gtk.Label(label="General"))

    def _on_browse_log_path(self, _button):
        dialog = Gtk.FileChooserDialog(
            title="Select Log File",
            transient_for=self.window,
            action=Gtk.FileChooserAction.SAVE,
        )
        dialog.add_button(Gtk.STOCK_CANCEL, Gtk.ResponseType.CANCEL)
        dialog.add_button(Gtk.STOCK_SAVE, Gtk.ResponseType.ACCEPT)
        dialog.set_filename(self._log_path_entry.get_text())
        if dialog.run() == Gtk.ResponseType.ACCEPT:
            self._log_path_entry.set_text(dialog.get_filename())
        dialog.destroy()

    # ------------------------------------------------------------------
    # Tab 2 — Model
    # ------------------------------------------------------------------

    def _create_model_tab(self, notebook):
        grid = Gtk.Grid()
        grid.set_row_spacing(6)
        grid.set_column_spacing(6)
        grid.set_margin_top(12)
        grid.set_margin_bottom(12)
        grid.set_margin_start(12)
        grid.set_margin_end(12)

        row = 0

        # Tier
        self._tier_combo = self._make_combo(["tiny", "small", "medium"])
        self._tier_combo.connect("changed", self._on_tier_changed)
        self._add_grid_row(grid, row, "Tier", self._tier_combo)
        row += 1

        # Model path (custom override)
        self._model_path_entry = Gtk.Entry()
        self._model_path_entry.set_placeholder_text("Auto-detect (empty = default)")
        self._add_grid_row(grid, row, "Model Path", self._model_path_entry)
        row += 1

        # Dict path (custom override)
        self._dict_path_entry = Gtk.Entry()
        self._dict_path_entry.set_placeholder_text("Auto-detect (empty = default)")
        self._add_grid_row(grid, row, "Dict Path", self._dict_path_entry)
        row += 1

        # Auto-download
        self._auto_download_check = Gtk.CheckButton(label="Auto-download model if missing")
        grid.attach(self._auto_download_check, 0, row, 2, 1)
        row += 1

        # Download timeout
        self._download_timeout_spin = self._make_spin(10, 120)
        self._download_timeout_spin.set_value(30)
        self._add_grid_row(grid, row, "Download Timeout (s)", self._download_timeout_spin)
        row += 1

        # Download button + progress bar
        dl_hbox = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=6)
        self._download_button = Gtk.Button(label="Download Model")
        self._download_button.connect("clicked", self._on_download_model)
        dl_hbox.pack_start(self._download_button, False, False, 0)

        self._download_progressbar = Gtk.ProgressBar()
        self._download_progressbar.set_visible(False)
        self._download_progressbar.set_hexpand(True)
        dl_hbox.pack_start(self._download_progressbar, True, True, 0)
        grid.attach(dl_hbox, 0, row, 2, 1)
        row += 1

        # Separator
        sep = Gtk.HSeparator()
        grid.attach(sep, 0, row, 2, 1)
        row += 1

        # Model info display
        self._model_info_label = Gtk.Label()
        self._model_info_label.set_halign(Gtk.Align.START)
        self._model_info_label.set_valign(Gtk.Align.START)
        self._model_info_label.set_margin_top(4)
        grid.attach(self._model_info_label, 0, row, 2, 1)

        swin = Gtk.ScrolledWindow()
        swin.set_policy(Gtk.PolicyType.AUTOMATIC, Gtk.PolicyType.AUTOMATIC)
        swin.add(grid)
        notebook.append_page(swin, Gtk.Label(label="Model"))

    # -- model download logic ------------------------------------------------

    def _on_download_model(self, _button):
        if self._download_in_progress:
            return
        self._download_in_progress = True
        self._download_button.set_sensitive(False)
        self._download_progressbar.set_visible(True)

        # Pulse every 100 ms while download is running
        self._pulse_id = GLib.timeout_add(100, self._pulse_progress)

        model_cfg = {
            "tier": self._tier_combo.get_active_id() or "small",
            "download_path": self.config["model"].get(
                "download_path",
                "/usr/local/share/ibus-handwrite-chinese/models",
            ),
            "auto_download": True,
            "download_timeout": int(self._download_timeout_spin.get_value()),
        }
        thread = threading.Thread(target=self._do_download, args=(model_cfg,))
        thread.daemon = True
        thread.start()

    def _pulse_progress(self):
        if self._download_in_progress:
            self._download_progressbar.pulse()
            return True
        self._download_progressbar.set_visible(False)
        return False

    def _do_download(self, model_cfg):
        try:
            handwrite_model_download.ensure_model(model_cfg)
            GLib.idle_add(self._on_download_success)
        except Exception as exc:
            GLib.idle_add(self._on_download_error, str(exc))

    def _on_download_success(self):
        self._download_in_progress = False
        self._download_button.set_sensitive(True)
        if self._pulse_id is not None:
            GLib.source_remove(self._pulse_id)
            self._pulse_id = None
        self._refresh_model_info()

        md = Gtk.MessageDialog(
            transient_for=self.window,
            flags=0,
            message_type=Gtk.MessageType.INFO,
            buttons=Gtk.ButtonsType.OK,
            text="Model downloaded successfully",
        )
        md.format_secondary_text(
            "The PP-OCRv6 model and dictionary are ready for use."
        )
        md.run()
        md.destroy()

    def _on_download_error(self, error_msg):
        self._download_in_progress = False
        self._download_button.set_sensitive(True)
        if self._pulse_id is not None:
            GLib.source_remove(self._pulse_id)
            self._pulse_id = None

        md = Gtk.MessageDialog(
            transient_for=self.window,
            flags=0,
            message_type=Gtk.MessageType.ERROR,
            buttons=Gtk.ButtonsType.OK,
            text="Download failed",
        )
        md.format_secondary_text(error_msg)
        md.run()
        md.destroy()

    def _refresh_model_info(self):
        tier = self._tier_combo.get_active_id()
        if not tier:
            self._model_info_label.set_text("Select a model tier.")
            return
        download_path = self.config["model"].get(
            "download_path",
            "/usr/local/share/ibus-handwrite-chinese/models",
        )
        try:
            info = handwrite_model_download.model_info(download_path, tier)
            lines = []
            if info["model_exists"]:
                lines.append(
                    f"Model: {info['model_size_mb']:.1f} MB"
                )
                if info["last_modified"]:
                    lines.append(f"Modified: {info['last_modified']}")
            else:
                lines.append("Model: not downloaded")

            if info["dict_exists"]:
                lines.append(f"Dictionary: {info['dict_lines']:,} entries")
            else:
                lines.append("Dictionary: not downloaded")

            self._model_info_label.set_text("\n".join(lines))
        except Exception:
            self._model_info_label.set_text("Model info not available.")

    def _on_tier_changed(self, combo):
        tier = combo.get_active_id()
        if not tier:
            return
        self._refresh_model_info()
        download_path = self.config["model"].get(
            "download_path",
            "/usr/local/share/ibus-handwrite-chinese/models",
        )
        model_exists, _ = handwrite_model_download.check_existing(download_path, tier)
        if not model_exists:
            dialog = Gtk.MessageDialog(
                transient_for=self.window,
                message_type=Gtk.MessageType.QUESTION,
                buttons=Gtk.ButtonsType.YES_NO,
                text=f"Model for '{tier}' tier not downloaded yet",
                secondary_text="Do you want to download it now?",
            )
            response = dialog.run()
            dialog.destroy()
            if response == Gtk.ResponseType.YES:
                self._on_download_model(None)

    # ------------------------------------------------------------------
    # Tab 3 — Engine
    # ------------------------------------------------------------------

    def _create_engine_tab(self, notebook):
        grid = Gtk.Grid()
        grid.set_row_spacing(6)
        grid.set_column_spacing(6)
        grid.set_margin_top(12)
        grid.set_margin_bottom(12)
        grid.set_margin_start(12)
        grid.set_margin_end(12)

        row = 0

        self._stroke_width_spin = self._make_spin(1, 20)
        self._add_grid_row(grid, row, "Stroke Width (px)", self._stroke_width_spin)
        row += 1


        self._page_size_spin = self._make_spin(4, 20)
        self._add_grid_row(grid, row, "Page Size", self._page_size_spin)
        row += 1

        self._max_candidates_spin = self._make_spin(8, 100)
        self._add_grid_row(grid, row, "Max Candidates", self._max_candidates_spin)
        row += 1

        self._min_redraw_ms_spin = self._make_spin(8, 100)
        self._add_grid_row(grid, row, "Min Redraw (ms)", self._min_redraw_ms_spin)
        row += 1

        self._momentum_decay_scale = self._make_scale(0.0, 1.0)
        self._add_grid_row(grid, row, "Momentum Decay", self._momentum_decay_scale)
        row += 1

        self._momentum_threshold_scale = self._make_scale(0.0, 1.0)
        self._add_grid_row(grid, row, "Momentum Threshold", self._momentum_threshold_scale)
        row += 1

        self._momentum_tick_ms_spin = self._make_spin(10, 200)
        self._add_grid_row(grid, row, "Momentum Tick (ms)", self._momentum_tick_ms_spin)
        row += 1

        self._auto_pause_debounce_ms_spin = self._make_spin(10, 500)
        self._add_grid_row(grid, row, "Auto-pause Debounce (ms)", self._auto_pause_debounce_ms_spin)
        row += 1

        self._delete_hold_ms_spin = self._make_spin(100, 2000)
        self._add_grid_row(grid, row, "Delete Hold (ms)", self._delete_hold_ms_spin)
        row += 1

        swin = Gtk.ScrolledWindow()
        swin.set_policy(Gtk.PolicyType.AUTOMATIC, Gtk.PolicyType.AUTOMATIC)
        swin.add(grid)
        notebook.append_page(swin, Gtk.Label(label="Engine"))

    # ------------------------------------------------------------------
    # Tab 4 — Window
    # ------------------------------------------------------------------

    def _create_window_tab(self, notebook):
        grid = Gtk.Grid()
        grid.set_row_spacing(6)
        grid.set_column_spacing(6)
        grid.set_margin_top(12)
        grid.set_margin_bottom(12)
        grid.set_margin_start(12)
        grid.set_margin_end(12)

        row = 0

        self._width_spin = self._make_spin(200, 1200)
        self._add_grid_row(grid, row, "Width (px)", self._width_spin)
        row += 1

        self._height_spin = self._make_spin(200, 800)
        self._add_grid_row(grid, row, "Height (px)", self._height_spin)
        row += 1

        self._drawing_height_spin = self._make_spin(100, 600)
        self._add_grid_row(grid, row, "Drawing Height (px)", self._drawing_height_spin)
        row += 1

        self._drag_handle_height_spin = self._make_spin(10, 50)
        self._add_grid_row(grid, row, "Drag Handle Height (px)", self._drag_handle_height_spin)
        row += 1

        self._candidate_button_width_spin = self._make_spin(20, 80)
        self._add_grid_row(grid, row, "Candidate Button Width (px)", self._candidate_button_width_spin)
        row += 1

        swin = Gtk.ScrolledWindow()
        swin.set_policy(Gtk.PolicyType.AUTOMATIC, Gtk.PolicyType.AUTOMATIC)
        swin.add(grid)
        notebook.append_page(swin, Gtk.Label(label="Window"))

    # ------------------------------------------------------------------
    # Tab 5 — User Dictionary
    # ------------------------------------------------------------------

    def _create_user_dict_tab(self, notebook):
        grid = Gtk.Grid()
        grid.set_row_spacing(6)
        grid.set_column_spacing(6)
        grid.set_margin_top(12)
        grid.set_margin_bottom(12)
        grid.set_margin_start(12)
        grid.set_margin_end(12)

        row = 0

        # Enabled
        self._ud_enabled_check = Gtk.CheckButton(label="Enable user dictionary")
        grid.attach(self._ud_enabled_check, 0, row, 2, 1)
        row += 1

        # Boost strength
        self._ud_boost_strength_scale = self._make_scale(1.0, 5.0)
        self._ud_boost_strength_scale.set_digits(1)
        self._add_grid_row(grid, row, "Boost Strength", self._ud_boost_strength_scale)
        row += 1

        # Max entries
        self._ud_max_entries_spin = self._make_spin(100, 100000)
        self._add_grid_row(grid, row, "Max Entries", self._ud_max_entries_spin)
        row += 1

        # Separator
        sep = Gtk.HSeparator()
        grid.attach(sep, 0, row, 2, 1)
        row += 1

        # Stats
        self._ud_stats_label = Gtk.Label(label="Loading…")
        self._ud_stats_label.set_halign(Gtk.Align.START)
        self._ud_stats_label.set_margin_top(4)
        grid.attach(self._ud_stats_label, 0, row, 2, 1)

        swin = Gtk.ScrolledWindow()
        swin.set_policy(Gtk.PolicyType.AUTOMATIC, Gtk.PolicyType.AUTOMATIC)
        swin.add(grid)
        notebook.append_page(swin, Gtk.Label(label="User Dictionary"))

    def _refresh_user_dict_stats(self):
        try:
            ud = handwrite_userdict.UserDict()
            stats = ud.get_stats()
            ud.close()
            total = stats.get("total", 0)
            top = stats.get("top", [])
            text = f"Learned characters: {total}"
            if top:
                top_str = ", ".join(f"{ch} ({n})" for ch, n in top[:5])
                text += f"\nTop entries: {top_str}"
            self._ud_stats_label.set_text(text)
        except Exception:
            self._ud_stats_label.set_text("Not available")

    # ------------------------------------------------------------------
    # Tab 6 — Shortcuts
    # ------------------------------------------------------------------

    def _create_shortcuts_tab(self, notebook):
        vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=4)
        vbox.set_margin_top(12)
        vbox.set_margin_bottom(12)
        vbox.set_margin_start(12)
        vbox.set_margin_end(12)

        # Header
        header_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=6)
        action_header = Gtk.Label(label="Action")
        action_header.set_halign(Gtk.Align.START)
        action_header.set_margin_end(6)
        binding_header = Gtk.Label(label="Shortcut")
        binding_header.set_halign(Gtk.Align.START)
        header_box.pack_start(action_header, False, False, 0)
        header_box.pack_start(binding_header, True, True, 0)
        vbox.pack_start(header_box, False, False, 0)

        sep = Gtk.HSeparator()
        vbox.pack_start(sep, False, False, 0)

        # Shortcut rows
        defaults = handwrite_shortcuts.get_default_bindings()

        for action in _SHORTCUT_ACTIONS:
            row_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=6)

            action_lbl = Gtk.Label(label=_SHORTCUT_LABELS.get(action, action))
            action_lbl.set_halign(Gtk.Align.START)
            action_lbl.set_size_request(120, -1)
            row_box.pack_start(action_lbl, False, False, 0)

            initial_key = self.config["shortcuts"].get(action, defaults.get(action, ""))
            entry = KeyCaptureEntry(action, initial_key)
            row_box.pack_start(entry, True, True, 0)
            self._shortcut_entries[action] = entry

            reset_btn = Gtk.Button(label="Reset")
            reset_btn.connect(
                "clicked",
                lambda _b, a=action, e=entry, d=defaults: e.set_key_string(d.get(a, "")),
            )
            row_box.pack_start(reset_btn, False, False, 0)

            vbox.pack_start(row_box, False, False, 0)

        # Separator
        vbox.pack_start(Gtk.HSeparator(), False, False, 6)

        # Reset All button
        reset_all_btn = Gtk.Button(label="Reset All to Defaults")
        reset_all_btn.connect("clicked", self._on_reset_shortcuts)
        vbox.pack_start(reset_all_btn, False, False, 0)

        swin = Gtk.ScrolledWindow()
        swin.set_policy(Gtk.PolicyType.AUTOMATIC, Gtk.PolicyType.AUTOMATIC)
        swin.add(vbox)
        notebook.append_page(swin, Gtk.Label(label="Shortcuts"))

    def _on_reset_shortcuts(self, _button):
        defaults = handwrite_shortcuts.get_default_bindings()
        for action, entry in self._shortcut_entries.items():
            entry.set_key_string(defaults.get(action, ""))

    # ------------------------------------------------------------------
    # Load / collect widget values
    # ------------------------------------------------------------------

    def _load_widget_values(self):
        c = self.config

        # General
        self._theme_combo.set_active_id(c["general"]["theme"])
        self._log_level_combo.set_active_id(c["general"]["log_level"])
        self._log_path_entry.set_text(c["general"]["log_path"])

        # Model
        self._tier_combo.set_active_id(c["model"]["tier"])
        self._model_path_entry.set_text(c["model"].get("path", ""))
        self._dict_path_entry.set_text(c["model"].get("dict_path", ""))
        self._auto_download_check.set_active(c["model"].get("auto_download", True))
        self._download_timeout_spin.set_value(c["model"].get("download_timeout", 30))

        # Engine
        self._stroke_width_spin.set_value(c["engine"]["stroke_width"])
        self._page_size_spin.set_value(c["engine"]["page_size"])
        self._max_candidates_spin.set_value(c["engine"]["max_candidates"])
        self._min_redraw_ms_spin.set_value(c["engine"]["min_redraw_ms"])
        self._momentum_decay_scale.set_value(c["engine"]["momentum_decay"])
        self._momentum_threshold_scale.set_value(c["engine"]["momentum_threshold"])
        self._momentum_tick_ms_spin.set_value(c["engine"]["momentum_tick_ms"])
        self._auto_pause_debounce_ms_spin.set_value(c["engine"]["auto_pause_debounce_ms"])
        self._delete_hold_ms_spin.set_value(c["engine"]["delete_hold_ms"])

        # Window
        self._width_spin.set_value(c["window"]["width"])
        self._height_spin.set_value(c["window"]["height"])
        self._drawing_height_spin.set_value(c["window"]["drawing_height"])
        self._drag_handle_height_spin.set_value(c["window"]["drag_handle_height"])
        self._candidate_button_width_spin.set_value(c["window"]["candidate_button_width"])

        # User Dict
        self._ud_enabled_check.set_active(c["user_dict"]["enabled"])
        self._ud_boost_strength_scale.set_value(c["user_dict"]["boost_strength"])
        self._ud_max_entries_spin.set_value(c["user_dict"]["max_entries"])

        # Shortcuts: entries already initialised in _create_shortcuts_tab
        # using config values; nothing to sync here.

    def _collect_config(self):
        """Read widget values into a full config dict (deep-copied from defaults)."""
        config = copy.deepcopy(handwrite_config.DEFAULT_CONFIG)

        # General
        config["general"]["theme"] = self._theme_combo.get_active_id() or "dark"
        config["general"]["log_level"] = self._log_level_combo.get_active_id() or "INFO"
        config["general"]["log_path"] = self._log_path_entry.get_text()

        # Model
        config["model"]["tier"] = self._tier_combo.get_active_id() or "small"
        config["model"]["path"] = self._model_path_entry.get_text()
        config["model"]["dict_path"] = self._dict_path_entry.get_text()
        config["model"]["auto_download"] = self._auto_download_check.get_active()
        config["model"]["download_timeout"] = int(self._download_timeout_spin.get_value())

        # Engine
        config["engine"]["stroke_width"] = int(self._stroke_width_spin.get_value())
        config["engine"]["page_size"] = int(self._page_size_spin.get_value())
        config["engine"]["max_candidates"] = int(self._max_candidates_spin.get_value())
        config["engine"]["min_redraw_ms"] = int(self._min_redraw_ms_spin.get_value())
        config["engine"]["momentum_decay"] = round(self._momentum_decay_scale.get_value(), 2)
        config["engine"]["momentum_threshold"] = round(self._momentum_threshold_scale.get_value(), 2)
        config["engine"]["momentum_tick_ms"] = int(self._momentum_tick_ms_spin.get_value())
        config["engine"]["auto_pause_debounce_ms"] = int(self._auto_pause_debounce_ms_spin.get_value())
        config["engine"]["delete_hold_ms"] = int(self._delete_hold_ms_spin.get_value())

        # Window
        config["window"]["width"] = int(self._width_spin.get_value())
        config["window"]["height"] = int(self._height_spin.get_value())
        config["window"]["drawing_height"] = int(self._drawing_height_spin.get_value())
        config["window"]["drag_handle_height"] = int(self._drag_handle_height_spin.get_value())
        config["window"]["candidate_button_width"] = int(self._candidate_button_width_spin.get_value())

        # User Dict
        config["user_dict"]["enabled"] = self._ud_enabled_check.get_active()
        config["user_dict"]["boost_strength"] = round(self._ud_boost_strength_scale.get_value(), 1)
        config["user_dict"]["max_entries"] = int(self._ud_max_entries_spin.get_value())

        # Shortcuts
        for action, entry in self._shortcut_entries.items():
            config["shortcuts"][action] = entry.get_key_string()

        return config

    # ------------------------------------------------------------------
    # Button handlers
    # ------------------------------------------------------------------

    def _on_apply(self, _button):
        new_config = self._collect_config()
        config_path = self._get_config_path()

        try:
            write_toml(new_config, config_path)
            self.original_config = copy.deepcopy(new_config)

            md = Gtk.MessageDialog(
                transient_for=self.window,
                flags=0,
                message_type=Gtk.MessageType.INFO,
                buttons=Gtk.ButtonsType.OK,
                text="Settings saved",
            )
            md.format_secondary_text(
                f"Configuration written to {config_path}\n"
                "Restart the engine for changes to take effect."
            )
            md.run()
            md.destroy()
        except Exception as exc:
            md = Gtk.MessageDialog(
                transient_for=self.window,
                flags=0,
                message_type=Gtk.MessageType.ERROR,
                buttons=Gtk.ButtonsType.OK,
                text="Failed to save settings",
            )
            md.format_secondary_text(str(exc))
            md.run()
            md.destroy()

    def _on_cancel(self, _button):
        self.window.destroy()

    def _on_reset(self, _button):
        md = Gtk.MessageDialog(
            transient_for=self.window,
            flags=0,
            message_type=Gtk.MessageType.WARNING,
            buttons=Gtk.ButtonsType.YES_NO,
            text="Reset all settings to defaults?",
        )
        md.format_secondary_text(
            "This will discard all current changes and restore every value "
            "to its built-in default."
        )
        response = md.run()
        md.destroy()

        if response == Gtk.ResponseType.YES:
            self.config = copy.deepcopy(handwrite_config.DEFAULT_CONFIG)
            self._load_widget_values()
            self._refresh_model_info()
            self._refresh_user_dict_stats()


# ---------------------------------------------------------------------------
# Standalone entry point
# ---------------------------------------------------------------------------

def main():
    """Launch the preferences dialog.

    Call from standalone ``python3 handwrite_prefs.py`` or from the engine's
    ``--setup`` mode.  Blocks until the dialog is closed.
    """
    Gtk.init(sys.argv)
    prefs = HandwritePrefs()
    prefs.window.show_all()
    prefs.window.present()
    Gtk.main()


if __name__ == "__main__":
    main()
